### ISSUE TITLE
Repository input is missing in actions.yml

### ISSUE THREAD

**Issue by qlikcoe** [jerray/publish-docker-action#12]
It seems like `repository` input is missing in the list of allowed actions (https://github.com/jerray/publish-docker-action/blob/master/action.yml), thus giving this error: 

```
##[warning]Unexpected input 'repository', valid inputs are ['username', 'password', 'registry', 'file', 'path', 'tags', 'build_args', 'target', 'allow_pull_request', 'auto_tag', 'cache']
```

**Comment by jerray** [comment]
Sorry. I'll fix it in next release.
Thank you for your feedback.
