### ISSUE TITLE
Standard-version CLI, tag seems to get ignored

### ISSUE THREAD

**Issue by StiviiK** [jerray/publish-docker-action#16]
Hi I am trying to to use the `standard-version` (npm) cli to generate a new version using GitHub Actions and the build and push the Image but only the latest tag seems to get pushed:
```
- run: |
    cd src/controller
    yarn install

    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    yarn generate:version
- uses: jerray/publish-docker-action@master
  with:
    registry: ghcr.io
    username: ${{ secrets.GCR_USERNAME }}
    password: ${{ secrets.GCR_PASSWORD }}
    repository: ***
    path: ./src/controller/
    file: ./src/controller/Dockerfile
    auto_tag: true
```

package.json
```
{
  "name": "controller",
  "version": "0.0.0",
  "scripts": {
    "generate:version": "standard-version --path ."
  },
  "license": "MIT",
  "devDependencies": {
    "standard-version": "^9.0.0"
  }
}
```

**Comment by jerray** [comment]
@StiviiK  `auto_tag` depends on current git reference (branch, pull request or tag) which triggers the workflow. This is why tags generated in workflow are ignored. I don't know much about `standard-version`, but I think https://github.com/jerray/publish-docker-action/issues/11#issuecomment-607077257 may help.

**Comment by StiviiK** [comment]
This is helpful, thank you!
