### ISSUE TITLE
Export computed tag for a further action

### ISSUE THREAD

**Issue by thom4parisot** [jerray/publish-docker-action#9]
Hello!

Thanks for this action, it's been very useful to me and the project I use it for.

Here is my question: when the `auto_tags` option is activated, is there a way to reuse the computed Docker tag for a further build step?

My use case is then to deploy the tagged image on a remote machine/send a notification with the image pull instructions.

Thanks a bunch for your answer.

**Comment by jerray** [comment]
@oncletom Thanks for your great advice. I'll implement this feature in next few days.

**Comment by jerray** [comment]
@oncletom Hi! I just released a new version v1.0.4. Here's a sample workflow [main.yml](https://github.com/jerray/hello-world/blob/master/.github/workflows/main.yml). Now you can try it in your own project.

**Comment by thom4parisot** [comment]
Aaaah, amazing 🙂 

I totally forgot about the `output` thingy! Thanks for making it happen, and for documenting it in the README, clearly where I expected it.
